# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FCS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  # Pods for FCS

  target 'FCSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FCSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
